# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCadastrouserlogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadastrouserlogin(self):
    # Test name: cadastro_user_login
    # Step # | name | target | value
    # 1 | open | /welcome | 
    self.driver.get("http://localhost:4200/welcome/welcome")
    # 2 | setWindowSize | 1920x1080 | 
    self.driver.set_window_size(1920, 1080)
    # 3 | click | id=cadastro | 
    self.driver.find_element(By.ID, "cadastro").click()
    # 4 | type | id=password | %mC>)9's#:EsQ>z
    self.driver.find_element(By.ID, "password").send_keys("%mC>)9\'s#:EsQ>z")
    # 5 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 6 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 7 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 8 | doubleClick | id=username | 
    element = self.driver.find_element(By.ID, "username")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 9 | type | id=username | gustavo1
    self.driver.find_element(By.ID, "username").send_keys("gustavo1")
    # 10 | click | css=app-user-registration | 
    self.driver.find_element(By.CSS_SELECTOR, "app-user-registration").click()
    # 11 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 12 | type | id=email | gustavo1@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("gustavo1@gmail.com")
    # 13 | click | css=app-user-registration | 
    self.driver.find_element(By.CSS_SELECTOR, "app-user-registration").click()
    # 14 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 15 | type | id=password | gustavo1
    self.driver.find_element(By.ID, "password").send_keys("gustavo1")
    # 16 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 17 | type | id=password | %mC>)9's#:EsQ>z
    self.driver.find_element(By.ID, "password").send_keys("%mC>)9\'s#:EsQ>z")
    # 18 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 19 | type | id=username | gustavo1
    self.driver.find_element(By.ID, "username").send_keys("gustavo1")
    # 20 | click | css=app-login | 
    self.driver.find_element(By.CSS_SELECTOR, "app-login").click()
    # 21 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 22 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 23 | doubleClick | id=password | 
    element = self.driver.find_element(By.ID, "password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 24 | type | id=password | gustavo1
    self.driver.find_element(By.ID, "password").send_keys("gustavo1")
    # 25 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
